### ISSUE TITLE
工作平台停留在邮件界面后一段时间不操作，会死机

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-project-fssh#2]

**Comment by chenzhipei** [comment]
此问题是客户电脑安装的杀毒软件导致，后尹科长也没有反馈过相关现象

**Comment by hotlong** [comment]
尹科长提出，可能是因为集团邮件系统每两个小时自动注销导致的。
看能不能有一个定时的脚本，每个小时去连接一下服务器的一个请求，避免被自动注销。

**Comment by chenzhipei** [comment]
已处理，本地测试通过，待更新抚顺服务器
